lib/AppInfo/Application.php

Check whether the $_SERVER dict has the key 'REQUEST_METHOD' before accessing it. This fixes the periodic error in the logs that appears if the background jobs are handled by cron, i.e. cron.php is called by the PHP cli and thus no request method is set.

Check if $_SERVER has key before access. (#19)

---

README.md
lib/Controller/LoginController.php

I'm making the developer making developer settings https://github.com/pulsejet/nextcloud-oidc-login/tree/master/3rdparty/jumbojett/openid-connect-php#development-environments available via `config.php`

Improve developer setup by allowing to disable TLS verification

---

README.md
lib/AppInfo/Application.php
lib/Controller/LoginController.php

Allows home directories to be mounted using external storage instead of soft links. 
This has two advantages:
1. It allows existing home directories to be exported to nextcloud (there is no nextcloud-specific folder structure created beneath them)
2. It prevents nextcloud from deleting the home directory when a user is removed 
The symlink behavior is retained by default for backwards compatibility
Closes #29

Mount Home Directory as External Storage

---

lib/Controller/LoginController.php

Do not overwriting name and mail when they are explicitly set to null

Fix #57: Do not overwriting name and mail when null

---

README.md
lib/Controller/LoginController.php

You might want to add new groups from oicd by default.
This commit adds new groups if they are not already existing.
This behavior can be modified through the oidc_create_groups flag,
which is default to false to not alter current default behavior.

Create new groups

---

lib/Controller/LoginController.php

We have the following issue. our nextcloud-server (at version 9 upgraded
from owncloud) has the following problem:
Due to changes in the owncloud-code (around version 7 or 8) and
subsequent changes to our ldap-servers, we have three different internal
userid's for oc_ldap_user_mapping in the field owncloud_name:
> | ldap_dn                                 | owncloud_name                         | directory_uuid |
> | cn=type01,ou=angehoerige,o=XXX          | 0012345-6789-0101-2222-3344556677     | type01         |
> | cn=type02,ou=angehoerige,o=XXX          | 001234567890                          | type02         |
> | cn=type03,ou=angehoerige,o=XXX          | type03                                | type03         |
Since we are talking here about ~3000 users, and about 1200 have the …

Fix: LdapID Mapping problem

---

README.md

I feel like an idiot opening this PR... :) 
I had some issues with Nextcloud resetting user quotas, as documented here:
https://www.reddit.com/r/NextCloud/comments/mrtfys/nextcloud_21_quota_keeps_getting_reset/
I thought this was the result of a bug. It's really not. I just didn't realize that the `oidc_login_default_quota` is optional, and that setting it will result in the behavior described in my post on the `r/NextCloud` subreddit.
This pull request contains no modifications to the code. There is just one minor update to the documentation. I'm hoping that maybe people can avoid the aggravation I had to deal with for a few days.
Thanks
--Steve

Minor clarification in the README

---

lib/Controller/LoginController.php

The user folder is not automatically created when the user already exists, but has never logged in before. `completeLogin` does not create the folder in this case due to token provided token. This missing folder prevents the user from accessing Nextcloud.
See issue https://github.com/pulsejet/nextcloud-oidc-login/issues/104
Thanks to https://github.com/zorn-v for the proposed solution.

First login failed for existing user

---

README.md
lib/Controller/LoginController.php

This PR adds optional feature that use profile attributes (claims) from ID Token, instead of UserInfo endpoint.
For example, Azure AD suggest to use ID Token instead of their UserInfo API ( https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo#consider-use-an-id-token-instead ), and in fact, some claims like 'preferred_username', 'groups' are not supported on AAD's UserInfo.
You can enable this feature with `'oidc_login_use_id_token' => true`.

Add the feature that use profile attributes from ID Token

---

README.md
lib/AppInfo/Application.php
lib/Controller/LoginController.php
lib/Provider/OpenIDConnectClient.php
lib/Service/LoginService.php
lib/WebDAV/BearerAuthBackend.php

This PR adds the ability to allow WebDAV access using an OIDC bearer token. This can be useful when using [rclone WebDAV with OIDC](https://rclone.org/webdav/#openid-connect) to synchronize a users files from Nextcloud.
To avoid too much load on the OIDC provider, this PR also adds caching of the JWKs as well as the discovered OIDC configuration for a configurable amount of time.
I suggest reviewing this PR by going through the commits. I tried to make each commit a logical unit of change to aid in the review. 
You can use the following script to test this functionality. To pass the tokens `audience` check in the `OpenIDConnectClient.php`, you will need to configure an audience mapper in Keycloak to ensure that your client is included in the `aud` property of the JWT. A [hardcoded …

Add WebDAV access using OIDC bearer token

---

README.md
lib/AppInfo/Application.php
lib/Controller/LoginController.php
lib/Provider/OpenIDConnectClient.php

We are using your OIDC login plugin to authenticate with our OIDC provider, but found that it does not support to logout the user with the OIDC provider.
I have added this feature in my own repository and it works in our DEV/STAGING environment.
I am not an experienced PHP developer so a close review would be definitely recommended. (resolves #113)

implement OIDC logout

---

lib/Provider/OpenIDConnectClient.php
lib/WebDAV/BearerAuthBackend.php

Hi. I have this setup:
- [canaille](https://gitlab.com/yaal/canaille) as my identity provider
- nextcloud + nextcloud-oidc-login as my resource server for carddav contacts
- roundcube + [rcmcarddav](https://github.com/mstilkerich/rcmcarddav) as my OIDC client, that wants to access the carddav contacts
As discussed in [this bug report](https://github.com/mstilkerich/rcmcarddav/issues/354) it seems that identity providers like Keycloak provide JWT access tokens, although it is not required by the specifications. nextcloud-oidc-login expects access token to be JWT but some providers like canaille do not provide JWT access token, but regular ones.
This patch allows WebDAV authentication with a regular access token. When a non-JWT token is detected (not dot in the string) requests are made on …

Allow WebDAV authentication with non JWT tokens

---

lib/Provider/OpenIDConnectClient.php

This fixes an issue which currently exists with IdentityServer. As mentioned in #120 the newly introduced caching doesn't work for the JWKS URL. (for IS this is located at a path below .well-known)
(fixes #120)

Fix integration with IdentityServer

---

README.md
lib/AppInfo/Application.php
lib/WebDAV/BasicAuthBackend.php

This follows #99 and fixes #128 by allowing `Basic` DAV authentication when `oidc_login_password_authentication` is set to `true` in the configuration.
This is useful for DAV clients that do not support `Bearer` authentication yet, [such as DAVx⁵](https://forums.bitfire.at/topic/2229/feature-request-oauth-support/8?_=1635183282657) or [GNOME Online Accounts](https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/178).
This use OAuth2 resource owner password flow, that is avoided nowadays and [might be forbidden](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-13#section-3.4) in the future. However, [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-4.3) tells us that:
> The authorization server should take special care when
>   enabling this …

DAV Password authentication

---

lib/Controller/LoginController.php
lib/Service/LoginService.php
lib/WebDAV/BasicAuthBackend.php
lib/WebDAV/BearerAuthBackend.php

This is a port of #154 for `BasicAuthBackend.php`

webdav Basic auth: login with user token

---

lib/AppInfo/Application.php
lib/Service/LoginService.php
lib/WebDAV/BasicAuthBackend.php

This allows clients that still use the `/remote.php/webdav` endpoint, such as [GNOME Online Accounts](https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/67) to authenticate against a OIDC identity provider with user and password.
It registers the `BasicAuthBackend` on the `addPlugin` event [raised in v1/webdav.php](
https://github.com/nextcloud/server/blob/a353db2c316773d680f8cfedf036c2b9bc54c16e/apps/dav/appinfo/v1/webdav.php#L80).
Then it avoids to execute session related operations, due to the session always being closed in this situation. I [detailed this issue on the nextcloud/server bugtracker](https://github.com/nextcloud/server/issues/31091), but to summarize, the default authentication backend plugged in the `remote.php/webdav` endpoint always closes the session before …

webdav endpoint v1 BasicAuthentication

---

lib/AppInfo/Application.php

Previously, we'd just redirect the user to the logout url, without
properly closing the session. This would lead to issues as described
in #115, where a user might be able to access another user's local
storage database.
As we hook into the postLogout event, which occurs during
the logout process, but not quite at the end of it, we have to do
some manual work to properly close the session.
(see https://github.com/nextcloud/server/blob/f9fb5f50dd1e4db8a81ad935c29f3490d1f9fa79/core/Controller/LoginController.php#L133-L147)
We now instruct the session the clear the execution contexts and
close it properly. Furthermore, we instruct the browser to clear
the associated cache and storage data.

Properly close session and clear browsers storage data on logout

---

README.md

Keycloak 18+ is disabling `redirect_uri` by default and will later be removed, see:
https://www.keycloak.org/2022/04/keycloak-1800-released

Update Readme for Keycloak 18+

---

README.md
lib/Provider/OpenIDConnectClient.php

Add the support of the Nextcloud HTTP proxy configuration.
Example: When a server is behind a firewall that obligate to use a given proxy for all HTTP(S) request, it's impossible to use this app.

Add Nextcloud proxy support

---

README.md
lib/Service/LoginService.php

Rebased from #111 by @djessich
Closes #111, closes #183, fixes #69
Support for group-based authroization is implemented in this commit. Only the configured group defined in plugin configuration is able to access Nextcloud. This authorized group is being read from optional 'oidc_login_authorized_group' configuration property.
In case the property is configured in plugin configuration and the user is not assigned to the configured group, the login will not be allowed for the user by failing the login process with an appropriate error message. The user groups will be read from OIDC response using the attribute configured in 'oidc_login_attributes' configuration property. When the user is not authorized, the user will neither be created nor its data will be updated in Nextcloud.
Fixes #69

Implements group-based authorization

---

README.md
lib/Provider/OpenIDConnectClient.php

This PR introduces the new optional config value `oidc_login_code_challenge_method` to be able to configure the PKCE flow. 
Signed-off-by: Robin Windey <ro.windey@gmail.com>

Implement PKCE flow (closing #134)

---

README.md
lib/Service/AttributeMap.php
lib/Service/LoginService.php

We use groups to control what shared folders users should be able to access.
We use a role to control which users are allowed to login to nextcloud.
So the 'oidc_login_allowed_groups' feature is not usable for use. In this pull request I added a 'oidc_login_allowed_roles' feature, which works with roles.

Add oidc_login_allowed_roles

---

appinfo/info.xml

According to https://github.com/pulsejet/nextcloud-oidc-login/issues/222#issuecomment-1590720857 it works with NC27, so let's bump it

Set compatibility to nc27

---

lib/Service/LoginService.php

In the login service, group display name and ID are mixed, causing users to be removed and added to the same group when a display name is set.
This problem sends notifications to the user (if enabled) and remove external storage on the desktop client (if external storage are disabled when added, the default behavior in the desktop client configuration).

Use group ID and not display name on remove

---

lib/Service/LoginService.php

Use `OC_Image->centerCrop()` to crop images automatically when updating avatar from OIDC provider.
Currently, non-square images raise an error, and thus can't be used as avatar. This PR fixes the issue.

Add auto centerCrop() when updating avatar

---

appinfo/info.xml

The plugin is deactivated after the upgrade to Nextcloud 30.
I have activated it manually and so far there have been no issues with NC v30.

Set compatibility to nc30

---

lib/Service/LoginService.php

Use public OCP\Image instead.
See https://github.com/nextcloud/server/pull/47535

fix: Move away from OC_Image

---

appinfo/info.xml

Nextcloud released Version 31 and this plugin is disabled. Error message:
`App "OpenID Connect Login" cannot be installed because it is not compatible with this version of the server.`
I have not tested if this app actually is compatible though ...

set max-version to 31
