pulsejet/nextcloud-oidc-login

README.md
Adds the instruction for Keycloak integration
=> Keycloak caveat

README.md, lib/Controller/LoginController.php
hi,
for my use case I needed to add a custom scope.
feedback would be appreciated
=> Adding Option for Changing The OpenID Connect Scope

lib/Controller/LoginController.php
With this change it is now possible to add the user to certain groups via a mapper (ownCloudGroups) or a variable.
=> Group feature

README.md
Changed and added some information to connect Keycloak with Nextcloud
=> README.md Keycloak Documentation optimized.

README.md
You already had most of the names right. 😁
=> Fix the rest of the Nextcloud names

README.md, css/oidc.css, lib/AppInfo/Application.php
Creating a new PR due to a conflict that complicated the earlier one.
=> Implement #26: 'Block user edit values given by OpenID.'

lib/Controller/LoginController.php
=> fix for email update problem

3rdparty/jumbojett/openid-connect-php/CHANGELOG.md, 3rdparty/jumbojett/openid-connect-php/README.md, 3rdparty/jumbojett/openid-connect-php/composer.json, 3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php, 3rdparty/jumbojett/openid-connect-php/tests/OpenIDConnectClientTest.php
v0.9.4 has [just been released](https://github.com/jumbojett/OpenID-Connect-PHP/releases/tag/v0.9.4)
=> Upgraded OpenID-Connect-PHP to version 0.9.4

appinfo/info.xml
Addresses #146 when released as new version.
=> Declare NC 23 compatibility

README.md
thanks for making this plugin!
=> Fix typo: minimalastic -> minimal*i*stic

lib/WebDAV/BearerAuthBackend.php
Previously, we'd login the WebDAV user only with a password.
However, this leads to issues, especially when using WebDAV (e.g.
with rclone) and the Nextcloud browser client in parallel. After
some time, the browser would refresh and log out the user. This
issue has been seen previously with the normal login flow as well
and was fixed in commit 3a50a43611d859daed44b065db86b16225052404.
=> webdav: Login user with token instead of password only

lib/Provider/OpenIDConnectClient.php
Previously, we would cache all responses from the IdP.
However, when the IdP or a reverse proxy in front of it
returns a non-200 code such as 500, we don't want to
cache the response. Caching the incorrect response would
prevent JWKs or the well-known configuration to be parsed
correctly and hence users from logging in.
Fixes #152
=> Only cache JWKs and well-known HTTP OK responses

README.md, lib/Service/LoginService.php
=> Update user avatars on login

3rdparty/jumbojett/openid-connect-php/CHANGELOG.md, 3rdparty/jumbojett/openid-connect-php/README.md, 3rdparty/jumbojett/openid-connect-php/composer.json, 3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php, 3rdparty/jumbojett/openid-connect-php/tests/OpenIDConnectClientTest.php, 3rdparty/jumbojett/openid-connect-php/tests/TokenVerificationTest.php
=> Bumped to OpenID-Connect-PHP 0.9.8

3rdparty/jumbojett/openid-connect-php/CHANGELOG.md, 3rdparty/jumbojett/openid-connect-php/README.md, 3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php, 3rdparty/jumbojett/openid-connect-php/tests/OpenIDConnectClientTest.php
=> Bump to OpenID-Connect-PHP 0.9.10

README.md
=> Improved documentation for oidc_login_disable_registration

appinfo/info.xml
Just tested. Seems to work fine.
Closes #197
=> Indicate we support Nextcloud 25

lib/Service/AttributeMap.php, lib/Service/LoginService.php, lib/WebDAV/BasicAuthBackend.php, lib/WebDAV/BearerAuthBackend.php
This is very high risk and needs to be reviewed carefully.
Closes #195
=> Reduce technical debt

lib/Service/LoginService.php
Logging in with token prevents skeleton files from being created. This change was a bug added during the big refactor of LoginService.
=> fix: login with password on first login (fix #144)

lib/Service/LoginService.php
Set a `If-Mofidied-Since` HTTP header on the avatar download request, and avoid to update the avatar if the return code is different than 200.
A complementary merge request could be to do the same thing with `ETag`.
Related to #219
=> Avoid to download and update avatars when they have not changed

README.md
=> docs: remove alt page default
